import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import yaml from 'js-yaml';
import { loadAgentManifest, loadFileIfExists, AgentManifest } from '../utils/loader.js';
import { loadAllSkills, getAllowedTools } from '../utils/skill-loader.js';
import { detectProvider } from './langchain-utils.js';

export function exportToLangChainString(dir: string): string {
  const agentDir = resolve(dir);
  const manifest = loadAgentManifest(agentDir);

  // Build system prompt (with knowledge + memory inlined)
  const systemPrompt = buildSystemPrompt(agentDir, manifest);

  // Build tools array
  const tools = buildToolDefinitions(agentDir, manifest);

  // Detect sub-agents
  const subAgents = buildSubAgentDefinitions(agentDir, manifest);

  // Detect memory config
  const hasMemory = existsSync(join(agentDir, 'memory', 'memory.yaml')) ||
                    existsSync(join(agentDir, 'memory', 'MEMORY.md'));

  // Determine LLM provider and model from manifest
  const model = manifest.model?.preferred ?? 'gpt-4o';
  const temperature = manifest.model?.constraints?.temperature ?? 0.7;
  const maxTokens = manifest.model?.constraints?.max_tokens;

  // Collect all providers needed (main + sub-agents)
  const mainProvider = detectProvider(model);
  if (!mainProvider) {
    throw new Error(
      `Model "${model}" is not supported by the LangChain adapter.\n` +
      'gitagent with LangChain currently supports OpenAI (gpt-*, o1-*, o3-*, …) and Anthropic (claude-*) only.'
    );
  }
  const allPipPackages = new Set<string>([mainProvider.pipPackage]);
  const allEnvVars = new Set<string>([mainProvider.envVar]);

  for (const sub of subAgents) {
    const subProv = detectProvider(sub.model ?? model);
    if (!subProv) {
      throw new Error(
        `Sub-agent model "${sub.model ?? model}" is not supported by the LangChain adapter.\n` +
        'gitagent with LangChain currently supports OpenAI (gpt-*, o1-*, o3-*, …) and Anthropic (claude-*) only.'
      );
    }
    allPipPackages.add(subProv.pipPackage);
    allEnvVars.add(subProv.envVar);
  }

  const pipPackages = ['langchain', ...allPipPackages];

  // Generate Python code for LangChain
  const lines: string[] = [];

  // --- Docstring ---
  lines.push('"""');
  lines.push(`LangChain agent definition for ${manifest.name} v${manifest.version}`);
  lines.push('Generated by gapman export');
  lines.push('');
  lines.push('Prerequisites:');
  lines.push(`  pip install ${pipPackages.join(' ')}`);
  lines.push('');
  lines.push('What is mapped:');
  lines.push('  - System prompt (SOUL.md, RULES.md, skills, compliance)');
  lines.push('  - Tool stubs from tools/*.yaml');
  lines.push('  - Model and temperature from agent.yaml');
  lines.push('  - Knowledge documents (always_load) inlined into system prompt');
  if (manifest.runtime?.max_turns) {
    lines.push('  - max_turns → recursion_limit');
  }
  if (hasMemory) {
    lines.push('  - Memory managed automatically by create_agent');
  }
  if (subAgents.length > 0) {
    lines.push(`  - Sub-agents as tool delegates: ${subAgents.map(s => s.name).join(', ')}`);
  }
  if (manifest.delegation) {
    lines.push('  - Delegation instructions embedded in system prompt');
  }
  lines.push('"""\n');

  // --- Imports (universal — no provider-specific imports) ---
  lines.push('import os');
  lines.push('import sys');
  lines.push('from langchain.chat_models import init_chat_model');
  lines.push('from langchain.agents import create_agent');
  lines.push('from langchain.tools import tool');
  lines.push('');

  // --- Tool stub definitions (module level — no API key needed) ---
  if (tools.length > 0) {
    lines.push('# --- Tool definitions ---\n');
    for (const t of tools) {
      const funcName = t.name.replace(/-/g, '_');
      lines.push('@tool');
      lines.push(`def ${funcName}(${t.params}) -> str:`);
      lines.push(`    """${t.description}"""`);
      lines.push('    # TODO: Implement tool logic');
      lines.push('    return "Not implemented"');
      lines.push('');
    }
  }

  // --- System prompt (module level) ---
  const escapedPrompt = systemPrompt
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '\\"\\"\\"');

  lines.push(`SYSTEM_PROMPT = """${escapedPrompt}"""`);
  lines.push('');

  // --- Main block ---
  // All model/agent creation happens here, AFTER env var checks,
  // so providers auto-detect API keys from environment variables.
  const envVarChecks = [...allEnvVars];
  const agentVarName = manifest.name.replace(/-/g, '_');

  lines.push('if __name__ == "__main__":');
  for (const envVar of envVarChecks) {
    lines.push(`    if not os.environ.get("${envVar}"):`);
    lines.push(`        print("Error: ${envVar} environment variable is not set")`);
    lines.push('        sys.exit(1)');
    lines.push('');
  }

  // Sub-agent delegates inside main (they require API keys)
  if (subAgents.length > 0) {
    lines.push('    # --- Sub-agent delegates ---');
    lines.push('    # Each sub-agent is a full agent the main agent can invoke via a tool.\n');

    for (const sub of subAgents) {
      const subVarName = sub.name.replace(/-/g, '_');
      const subModel = sub.model ?? model;
      const subTemp = sub.temperature ?? 0.7;

      const subPromptEscaped = sub.systemPrompt
        .replace(/\\/g, '\\\\')
        .replace(/"""/g, '\\"\\"\\"');

      const subModelArgs: string[] = [`"${subModel}"`, `temperature=${subTemp}`];

      lines.push(`    _${subVarName} = create_agent(`);
      lines.push(`        model=init_chat_model(${subModelArgs.join(', ')}),`);
      lines.push('        tools=[],');
      lines.push(`        system_prompt="""${subPromptEscaped}""",`);
      lines.push(`        name="${subVarName}",`);
      lines.push('    )');
      lines.push('');

      lines.push('    @tool');
      lines.push(`    def delegate_to_${subVarName}(query: str) -> str:`);
      lines.push(`        """${sub.description} — Delegate a task to the ${sub.name} sub-agent."""`);
      lines.push(`        result = _${subVarName}.invoke(`);
      lines.push('            {"messages": [{"role": "user", "content": query}]}');
      lines.push('        )');
      lines.push('        return result["messages"][-1].content');
      lines.push('');
    }
  }

  // Tools list (including sub-agent delegates + tool stubs)
  const allToolNames: string[] = [];
  for (const sub of subAgents) {
    allToolNames.push(`delegate_to_${sub.name.replace(/-/g, '_')}`);
  }
  for (const t of tools) {
    allToolNames.push(t.name.replace(/-/g, '_'));
  }

  if (allToolNames.length > 0) {
    lines.push(`    tools = [${allToolNames.join(', ')}]`);
  } else {
    lines.push('    tools = []');
  }
  lines.push('');

  // Model init args (no api_key — providers auto-detect from env vars)
  const modelInitArgs: string[] = [`"${model}"`, `temperature=${temperature}`];
  if (maxTokens) {
    modelInitArgs.push(`max_tokens=${maxTokens}`);
  }

  // Agent creation
  lines.push(`    ${agentVarName} = create_agent(`);
  lines.push(`        model=init_chat_model(${modelInitArgs.join(', ')}),`);
  lines.push('        tools=tools,');
  lines.push('        system_prompt=SYSTEM_PROMPT,');
  lines.push(`        name="${agentVarName}",`);
  lines.push('    )');
  lines.push('');

  // Invocation
  lines.push('    user_input = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Hello, what can you help me with?"');

  if (manifest.runtime?.max_turns) {
    lines.push(`    result = ${agentVarName}.invoke(`);
    lines.push('        {"messages": [{"role": "user", "content": user_input}]},');
    lines.push(`        {"recursion_limit": ${manifest.runtime.max_turns * 2}},`);
    lines.push('    )');
  } else {
    lines.push(`    result = ${agentVarName}.invoke(`);
    lines.push('        {"messages": [{"role": "user", "content": user_input}]}');
    lines.push('    )');
  }

  lines.push('    print(result["messages"][-1].content)');
  lines.push('');

  return lines.join('\n');
}

function buildSystemPrompt(agentDir: string, manifest: AgentManifest): string {
  const parts: string[] = [];

  // Agent identity header
  parts.push(`# ${manifest.name} v${manifest.version}`);
  parts.push(`${manifest.description}\n`);

  const soul = loadFileIfExists(join(agentDir, 'SOUL.md'));
  if (soul) parts.push(soul);

  const rules = loadFileIfExists(join(agentDir, 'RULES.md'));
  if (rules) parts.push(rules);

  const duties = loadFileIfExists(join(agentDir, 'DUTIES.md'));
  if (duties) parts.push(duties);

  // Skills — loaded via skill-loader
  const skillsDir = join(agentDir, 'skills');
  const skills = loadAllSkills(skillsDir);
  for (const skill of skills) {
    const toolsList = getAllowedTools(skill.frontmatter);
    const toolsNote = toolsList.length > 0 ? `\nAllowed tools: ${toolsList.join(', ')}` : '';
    parts.push(`## Skill: ${skill.frontmatter.name}\n${skill.frontmatter.description}${toolsNote}\n\n${skill.instructions}`);
  }

  // Knowledge (always_load documents) — inlined into prompt
  const knowledgeDir = join(agentDir, 'knowledge');
  const indexPath = join(knowledgeDir, 'index.yaml');
  if (existsSync(indexPath)) {
    const index = yaml.load(readFileSync(indexPath, 'utf-8')) as {
      documents?: Array<{ path: string; always_load?: boolean }>;
    };

    if (index.documents) {
      const alwaysLoad = index.documents.filter(d => d.always_load);
      for (const doc of alwaysLoad) {
        const content = loadFileIfExists(join(knowledgeDir, doc.path));
        if (content) {
          parts.push(`## Knowledge: ${doc.path}\n${content}`);
        }
      }
    }
  }

  // Compliance constraints
  if (manifest.compliance) {
    const c = manifest.compliance;
    const constraints: string[] = ['## Compliance Constraints'];

    if (c.supervision?.human_in_the_loop === 'always') {
      constraints.push('- All decisions require human approval before execution');
    }
    if (c.supervision?.escalation_triggers) {
      constraints.push('- Escalate to human supervisor when:');
      for (const trigger of c.supervision.escalation_triggers) {
        for (const [key, value] of Object.entries(trigger)) {
          constraints.push(`  - ${key}: ${value}`);
        }
      }
    }
    if (c.communications?.fair_balanced) constraints.push('- All communications must be fair and balanced (FINRA 2210)');
    if (c.communications?.no_misleading) constraints.push('- Never make misleading, exaggerated, or promissory statements');
    if (c.data_governance?.pii_handling === 'redact') constraints.push('- Redact all PII from outputs and intermediate reasoning');
    if (c.data_governance?.pii_handling === 'prohibit') constraints.push('- Do not process any personally identifiable information');

    if (c.segregation_of_duties) {
      const sod = c.segregation_of_duties;
      if (sod.assignments) {
        constraints.push('- Segregation of duties is enforced:');
        for (const [agentName, roles] of Object.entries(sod.assignments)) {
          constraints.push(`  - Agent "${agentName}" has role(s): ${roles.join(', ')}`);
        }
      }
      if (sod.conflicts) {
        constraints.push('- Duty separation rules (no single agent may hold both):');
        for (const [a, b] of sod.conflicts) {
          constraints.push(`  - ${a} and ${b}`);
        }
      }
      if (sod.enforcement === 'strict') {
        constraints.push('- SOD enforcement is STRICT — violations will block execution');
      }
    }

    if (constraints.length > 1) parts.push(constraints.join('\n'));
  }

  // Delegation instructions
  if (manifest.delegation) {
    const delParts: string[] = ['## Delegation'];
    delParts.push(`Mode: ${manifest.delegation.mode ?? 'manual'}`);
    if (manifest.agents) {
      delParts.push('Available sub-agents you can delegate to:');
      for (const [name, config] of Object.entries(manifest.agents)) {
        const funcName = `delegate_to_${name.replace(/-/g, '_')}`;
        delParts.push(`- Use the "${funcName}" tool to delegate to ${name}: ${config.description ?? ''}`);
        if (config.delegation?.triggers) {
          delParts.push(`  Triggers: ${config.delegation.triggers.join(', ')}`);
        }
      }
    }
    parts.push(delParts.join('\n'));
  }

  // Memory
  const memory = loadFileIfExists(join(agentDir, 'memory', 'MEMORY.md'));
  if (memory && memory.trim().split('\n').length > 2) {
    parts.push(`## Memory\n${memory}`);
  }

  return parts.join('\n\n');
}

interface SubAgentDef {
  name: string;
  description: string;
  model: string | undefined;
  temperature: number | undefined;
  systemPrompt: string;
}

function buildSubAgentDefinitions(agentDir: string, manifest: AgentManifest): SubAgentDef[] {
  const subAgents: SubAgentDef[] = [];

  if (!manifest.agents) return subAgents;

  for (const [name, config] of Object.entries(manifest.agents)) {
    const subDir = join(agentDir, 'agents', name);

    // Try to load the sub-agent's own manifest + SOUL
    let subModel: string | undefined;
    let subTemp: number | undefined;
    let subPromptParts: string[] = [];

    if (existsSync(join(subDir, 'agent.yaml'))) {
      try {
        const subManifest = loadAgentManifest(subDir);
        subModel = subManifest.model?.preferred;
        subTemp = subManifest.model?.constraints?.temperature;
        subPromptParts.push(`You are ${subManifest.name}: ${subManifest.description}`);
      } catch { /* ignore */ }
    }

    const subSoul = loadFileIfExists(join(subDir, 'SOUL.md'));
    if (subSoul) subPromptParts.push(subSoul);

    const subDuties = loadFileIfExists(join(subDir, 'DUTIES.md'));
    if (subDuties) subPromptParts.push(subDuties);

    // Fallback description
    if (subPromptParts.length === 0) {
      subPromptParts.push(config.description ?? `Sub-agent: ${name}`);
    }

    subAgents.push({
      name,
      description: config.description ?? `Delegate tasks to ${name}`,
      model: subModel,
      temperature: subTemp,
      systemPrompt: subPromptParts.join('\n\n'),
    });
  }

  return subAgents;
}

interface ToolDef {
  name: string;
  description: string;
  params: string;
}

function buildToolDefinitions(agentDir: string, _manifest: AgentManifest): ToolDef[] {
  const tools: ToolDef[] = [];
  const toolsDir = join(agentDir, 'tools');

  if (!existsSync(toolsDir)) return tools;

  const files = readdirSync(toolsDir).filter(f => f.endsWith('.yaml'));

  for (const file of files) {
    const content = readFileSync(join(toolsDir, file), 'utf-8');
    const toolConfig = yaml.load(content) as {
      name: string;
      description: string;
      input_schema?: {
        properties?: Record<string, { type: string }>;
        required?: string[];
      };
    };

    const params: string[] = [];
    if (toolConfig.input_schema?.properties) {
      for (const [name, schema] of Object.entries(toolConfig.input_schema.properties)) {
        const pyType = jsonTypeToPython(schema.type);
        const isRequired = toolConfig.input_schema.required?.includes(name);
        if (isRequired) {
          params.push(`${name}: ${pyType}`);
        } else {
          params.push(`${name}: ${pyType} = None`);
        }
      }
    }

    tools.push({
      name: toolConfig.name,
      description: toolConfig.description,
      params: params.join(', '),
    });
  }

  return tools;
}

function jsonTypeToPython(jsonType: string): string {
  switch (jsonType) {
    case 'string': return 'str';
    case 'integer': return 'int';
    case 'number': return 'float';
    case 'boolean': return 'bool';
    case 'array': return 'list';
    case 'object': return 'dict';
    default: return 'str';
  }
}
