"""
DeepAgents definition for research-assistant v1.0.0
Generated by gitagent export --format deepagents
"""

from __future__ import annotations

from deepagents import create_deep_agent
from langchain_core.tools import tool
from pathlib import Path

# Agent metadata
AGENT_NAME = "research-assistant"
AGENT_VERSION = "1.0.0"
MODEL = "anthropic:claude-sonnet-4-5"

# System prompt (SOUL.md + RULES.md + DUTIES.md + compliance)
SYSTEM_PROMPT = """# research-assistant
Research assistant with a fact-checker sub-agent

# Research Assistant

You are a research assistant. Find authoritative sources, extract the relevant
facts, and summarize them honestly. Delegate to the `fact-checker` sub-agent
whenever a claim warrants independent verification. Cite every claim.
"""

# Hooks (pre_tool_use scripts run before every tool call)
def _run_pre_tool_use_hooks(tool_name: str) -> None:
    """No pre_tool_use hooks configured in hooks/hooks.yaml."""
    return None

# NOTE: other hook events (post_tool_use, on_session_start, etc.) have no
# DeepAgents equivalent and are intentionally skipped.
# NOTE: memory/ has no direct DeepAgents equivalent — wire a checkpointer if needed.

# Tools (from tools/*.yaml)
@tool
def web_search(query: str) -> str:
    """Search the public web for a query"""
    _run_pre_tool_use_hooks("web-search")
    # TODO: replace this stub with a real implementation of "web-search"
    raise NotImplementedError("Implement tool: web-search")

TOOLS = [web_search]

# Skills (skills/<name>/SKILL.md — DeepAgents loads these natively)
# Resolved relative to this file so discovery works from any working directory.
SKILLS = [str(Path(__file__).resolve().parent / "skills")]

# For reference, the skills available in this agent:
#   - summarize: Condense the gathered sources into a faithful, cited summary
#   - web-research: Search the web for sources relevant to the user's question

# Sub-agents (agents/<name>/ → SubAgent dicts)
fact_checker_subagent = {
    "name": "fact-checker",
    "description": "Verifies factual claims against authoritative sources",
    "system_prompt": """# fact-checker
Verifies factual claims against authoritative sources

# Fact-Checker

You are a pedantic fact-checker. Treat every claim as unverified until you
locate a primary source. If a claim cannot be substantiated, say so plainly.
""",
    "tools": TOOLS,  # inherits the full parent toolset (default) — add `tools: [...]` to
    # this sub-agent's agent.yaml (agents/fact-checker/agent.yaml) to narrow it
}

SUBAGENTS = [fact_checker_subagent]

# Agent
agent = create_deep_agent(
    model=MODEL,
    system_prompt=SYSTEM_PROMPT,
    tools=TOOLS,
    skills=SKILLS,
    subagents=SUBAGENTS,
)

if __name__ == "__main__":
    import os
    user_input = os.environ.get("GITAGENT_PROMPT", "Hello")
    result = agent.invoke({"messages": [{"role": "user", "content": user_input}]})
    for message in result["messages"]:
        print(message)
